In [28]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn import preprocessing
from sklearn.feature_selection import SelectKBest, f_classif, f_regression



train_data = pd.read_csv("hw3_training_data.csv", sep=",")
test_data = pd.read_csv("hw3_test_data.csv", sep=",")
X_train = train_data.iloc[:, 0:6]
y_train = train_data.iloc[:, 6]


clf = svm.SVC(C=2.4, kernel='rbf', gamma=1e-5, cache_size=20000)
print(cross_val_score(clf, X_train, y_train, scoring='accuracy', cv=10))

[0.713 0.747 0.718 0.752 0.707 0.755 0.762 0.721 0.753 0.751]


In [5]:
[0.761 0.752 0.746 0.787 0.768 0.796 0.773 0.727 0.773 0.771]
[0.759 0.763 0.754 0.784 0.768 0.796 0.771 0.729 0.775 0.776]
X = X_train.values
y = y_train.values

# feature extraction
test = SelectKBest(k='all')
fit = test.fit(X, y)

# summarize scores
np.set_printoptions(precision=3)
print("Scores")
idx = 0
for score in fit.scores_:
    idx += 1
    print("Feature_{0}: {1} ".format(idx, score))
features = fit.transform(X)

Scores
Feature_1: 7.393392639785646 
Feature_2: 18.784669224696238 
Feature_3: 2.226012718737317 
Feature_4: 0.0004471250174478391 
Feature_5: 14.538376259304064 
Feature_6: 10.004583526480623 
